### ISSUE TITLE
GPU Crash

### ISSUE THREAD

**Issue by matteobsu** [astra-toolbox/astra-toolbox#179]
Dear ASTRA Community,

I’m writing you regarding a crash that is occurring when I’m trying to generate a large amount of training datasets using the ASTRA toolbox.
Basically the problem is that I’m running a series of GPU reconstruction using the algorithm SIRT_Cuda, and after a while my MATLAB crash because (I guess) the gpu runs out of memory.

In the loop I always clear all using the commands: 

                astra_mex_data2d('delete', rec_id);
                astra_mex_data2d('delete', sinogram_id);
                astra_mex_data2d('delete', alg_id);
                astra_mex_data2d('clear');

But that doesn’t really help. Do you have a clue of how can I solve this issue?

This is what I read in the matlab console when he crash occurs, and attached are the script I’m running and the crash log from MATLAB.

[Matlab_ASTRA_Log.txt](https://github.com/astra-toolbox/astra-toolbox/files/2644020/Matlab_ASTRA_Log.txt)

**Comment by matteobsu** [comment]
Hello guys,

Does anyone have a feedback on this? Latest version still crashes when I loop multiple reconstruction using CUDA.

Matteo

**Comment by wjp** [comment]
Dear Matteo,

The line `astra_mex_data2d('delete', alg_id);` should most likely be `astra_mex_algorithm('delete', alg_id);`. To avoid potential mix-ups like this, you can also use `astra_mex('delete', ...);` and it will automatically call the right module.

**Comment by matteobsu** [comment]
Thank you! It worked! Silly me I didn't notice the difference 👍

**Comment by wjp** [comment]
That's great to hear.
